### ISSUE TITLE
Missing .dlls

### ISSUE THREAD

**Issue by Nekkok** [Gegy/colored-lights#20]
Hi! I have this error that points to Iris but in the report points that some dll couldn't be found. How do I solve this?

UMPDC.dll
glfw.dll
lwjgl.dll
lwjgl_opengl.dll
lwjgl_stb.dll

[crash-2022-01-05_01.23.59-client.txt](https://github.com/Gegy/colored-lights/files/7811187/crash-2022-01-05_01.23.59-client.txt)

**Comment by Gegy** [comment]
Oh no, this is a very weird issue. It's best to report this to Iris, though, as Colored Lights can't be involved here. 🙂
