### ISSUE TITLE
CL doesn't read light colors from resource packs

### ISSUE THREAD

**Issue by hibiii** [Gegy/colored-lights#3]
Using a custom resource pack that sets green candles' lights are extremely green and purple candles' lights as extremely purple, you'd expect the candles to produce very colorful displays (brightness set to max):

![2021-05-09_23 01 47](https://user-images.githubusercontent.com/69405847/117597228-88114a80-b11b-11eb-8b77-aad9f98032d8.png)

Steps to reproduce:
1. Install and enable the example resource pack
2. Put a green or a purple candle, and light it with a flint and steel.

Modifying the `/assets/colored_lights/light_colors.json` file in the mod's archive doesn't work either. Additionally, you can't change existing colors with a resource pack.

[test_resourcepack.zip](https://github.com/Gegy/colored-lights/files/6448998/test_resourcepack.zip)

**Comment by Gegy** [comment]
This should be resolved since https://github.com/Gegy/colored-lights/commit/6ee9aa84e6dde3a4e7721d40d2fc787907fa5160 :)
